#!/usr/bin/env ruby -w

json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.vodafone.smartlife") # e.g. com.krausefx.app
