#!/usr/bin/env ruby -w

lane :beta do
  # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )
  # ...
end

fastlane beta
# To get a list of all available parameters for the gradle action, run:
fastlane action gradle